package edu.rice.comp610.model;

import java.util.Objects;
import java.util.UUID;

/**
 * Category of the item being put up for auction to help buyers find what they are looking for.
 *
 * <p>The category (classification) of the item being listed for auction.</p>
 * <ul>
 * <li> id - unique identifier generated by the system. </li>
 * <li> zelle_id - one or two work name for the category. </li>
 * <li> description - more detailed description of the category</li>
 * </ul>
 *
 */
public class PaymentDetail {

    private UUID id;
    private String zelleId;
    private UUID ownerId;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getZelleId() {
        return zelleId;
    }

    public void setZelleId(String zelleId) {
        this.zelleId = zelleId;
    }

    public UUID getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(UUID ownerId) {
        this.ownerId = ownerId;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PaymentDetail paymentDetail = (PaymentDetail) o;
        return Objects.equals(id, paymentDetail.id)
                && Objects.equals(zelleId, paymentDetail.zelleId)
                && Objects.equals(ownerId, paymentDetail.ownerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(zelleId, ownerId);
    }

    @Override
    public String toString() {
        return "Category{" +
                "id=" + id +
                ", zelle_id='" + zelleId + '\'' +
                ", owner_id='" + ownerId +
                '}';
    }
}
