package edu.rice.comp610.model;

import java.util.Objects;
import java.util.UUID;

/**
 * Buyer ratings of sellers.
 *
 * <p>Buyers rating of the sellers.</p>
 * <ul>
 * <li> id - unique identifier generated by the system. </li>
 * <li> rating - buyer rating of the seller (double). </li>
 * <li> raterId - the raters uuid </li>
 * <li> sellerId - the sellers uuid </li>
 * </ul>
 *
 */
public class Rating {

    private UUID id;
    private Double rating;
    private UUID raterId;
    private UUID sellerId;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getRaterId() {
        return raterId;
    }

    public void setRaterId(UUID raterId) {
        this.raterId = raterId;
    }

    public UUID getSellerId() {
        return sellerId;
    }

    public void setSellerId(UUID sellerId) {
        this.sellerId = sellerId;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Rating rating1 = (Rating) o;
        return Objects.equals(id, rating1.id)
                && Objects.equals(rating, rating1.rating)
                && Objects.equals(raterId, rating1.raterId)
                && Objects.equals(sellerId, rating1.sellerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rating, raterId, sellerId);
    }

    @Override
    public String toString() {
        return "Category{" +
                "id=" + id +
                ", rater_id='" + raterId + '\'' +
                ", seller_id='" + sellerId + '\'' +
                ", rating=" + rating +
                '}';
    }
}
