name: Deploy to Heroku with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Setup Python
        uses: actions/setup-python@4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install psycopg2
        run: pip install psycopg2
      - name: Clean and Install Maven
        run: mvn clean install
      - name: Build with Maven
        run: mvn compile
      - name: Test
        run: mvn test
      - name: JavaDoc
        run: mvn javadoc:javadoc
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: mvn heroku:deploy

