name: Deploy to Heroku with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Clean and Install Maven
        run: mvn clean install
      - name: Build with Maven
        run: mvn compile
      - name: Test
        run: mvn test
      - name: Deploy
        run: mvn heroku:deploy
