name: Run Database Schema Migrations

on:
  workflow_dispatch:
    inputs:
      db_name:
        description: 'Database Name to connect to'
        required: true
      db_host:
        description: 'Hostname or IP of PostgreSQL instance to connect to'
        required: true
      db_port:
        description: 'Port number of PostgreSQL instance to connect to'
        required: true
        default: '5432'
      db_user:
        description: 'Username to authenticate with'
        required: true
      db_password:
        description: 'Password to authenticate with'

jobs:
  migrateDBSchema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install psycopg2
        run: pip install psycopg2
      - name: Run migrations
        run: |
          cd database
          echo "Available Python migration files"
          python migrator.py list
          echo "Running migrate up"
          python migrator.py migrate --db-name ${{ github.event.inputs.db_name }} --db-host ${{ github.event.inputs.db_host }} --db-port ${{ github.event.inputs.db_port }} --db-user ${{ github.event.inputs.db_user }} --db-password ${{ github.event.inputs.db_password }} up
          echo "Finished migration, here are the migrations that have been run against the DB"
          python migrator.py migrate --db-name ${{ github.event.inputs.DB_NAME }} --db-host ${{ github.event.inputs.db_host }} --db-port ${{ github.event.inputs.db_port }} --db-user ${{ github.event.inputs.db_user }} --db-password ${{ github.event.inputs.db_password }} list
